'''
This script was generated by an AI model called Big Pickle on an open source terminal
AI Agent coding assistant called OpenCode.
The purpose was to integrate with GenAI and AI Agents to help seed my database
The agent was able to read my codebase and understand my sqlalchemy table structure, it's classes, and methods
and used my methods to seed the database.

This demonstrates the workflow that is possible with using AI to help produce software and automating
mundane manual tasks.
'''

from datetime import datetime, timedelta
from decimal import Decimal
import random

from dotenv import load_dotenv
from faker import Faker
from sqlalchemy import select

from models import config, enums
from models.transactions import Transactions
from models.savings_goals import SavingsGoals
from models.debts import Debts
from models.crypto_holding import CryptoHolding

load_dotenv()

fake = Faker()
Faker.seed(42)
random.seed(42)


def check_transactions_exist():
    stmt = select(Transactions.id).limit(1)
    result = config.session.execute(stmt).scalar_one_or_none()
    return result is not None


def check_savings_goal_exists(name: str):
    stmt = select(SavingsGoals).where(SavingsGoals.name == name)
    return config.session.execute(stmt).scalars().first() is not None


def check_debt_exists(name: str):
    stmt = select(Debts).where(Debts.name == name)
    return config.session.execute(stmt).scalars().first() is not None


def check_crypto_exists(symbol: str):
    stmt = select(CryptoHolding).where(CryptoHolding.symbol == symbol)
    return config.session.execute(stmt).scalars().first() is not None


def seed_savings_goals():
    if check_savings_goal_exists("House Down Payment") or check_savings_goal_exists("Emergency Fund"):
        print("Savings goals already exist, skipping...")
        return

    goals = [
        SavingsGoals(
            name="House Down Payment",
            target_amount=Decimal("50000.00"),
            current_amount=Decimal("20000.00"),
            deadline=datetime(2028, 6, 1),
            monthly_contribution=Decimal("800.00"),
            status=enums.SavingsGoalsStatusEnum.active,
        ),
        SavingsGoals(
            name="Emergency Fund",
            target_amount=Decimal("10000.00"),
            current_amount=Decimal("3000.00"),
            deadline=datetime(2027, 1, 1),
            monthly_contribution=Decimal("200.00"),
            status=enums.SavingsGoalsStatusEnum.active,
        ),
    ]

    for goal in goals:
        goal.add_SavingsGoals(config.session)
        print(f"Added savings goal: {goal.name}")


def seed_debts():
    if check_debt_exists("Student Loan") or check_debt_exists("Chase Credit Card") or check_debt_exists("Discover Credit Card"):
        print("Debts already exist, skipping...")
        return

    debts = [
        Debts(
            name="Student Loan",
            balance=Decimal("22500.00"),
            interest_rate=Decimal("5.50"),
            minimum_payment=Decimal("250.00"),
            debt_type=enums.DebtsTypeEnum.student_loan,
        ),
        Debts(
            name="Chase Credit Card",
            balance=Decimal("3200.00"),
            interest_rate=Decimal("22.99"),
            minimum_payment=Decimal("100.00"),
            debt_type=enums.DebtsTypeEnum.credit_card,
        ),
        Debts(
            name="Discover Credit Card",
            balance=Decimal("1800.00"),
            interest_rate=Decimal("19.99"),
            minimum_payment=Decimal("50.00"),
            debt_type=enums.DebtsTypeEnum.credit_card,
        ),
    ]

    for debt in debts:
        debt.add_debt(config.session)
        print(f"Added debt: {debt.name}")


def seed_crypto_holdings():
    if check_crypto_exists("btc") or check_crypto_exists("eth") or check_crypto_exists("sol") or check_crypto_exists("doge"):
        print("Crypto holdings already exist, skipping...")
        return

    holdings = [
        CryptoHolding(
            name="Bitcoin",
            symbol="btc",
            quantity=Decimal("0.50000000"),
            avg_purchase_price=Decimal("45000.00"),
            exchange=enums.CryptoHoldingExchangeEnum.coinbase,
        ),
        CryptoHolding(
            name="Ethereum",
            symbol="eth",
            quantity=Decimal("4.00000000"),
            avg_purchase_price=Decimal("2500.00"),
            exchange=enums.CryptoHoldingExchangeEnum.coinbase,
        ),
        CryptoHolding(
            name="Solana",
            symbol="sol",
            quantity=Decimal("25.00000000"),
            avg_purchase_price=Decimal("100.00"),
            exchange=enums.CryptoHoldingExchangeEnum.coinbase,
        ),
        CryptoHolding(
            name="Dogecoin",
            symbol="doge",
            quantity=Decimal("10000.00000000"),
            avg_purchase_price=Decimal("0.15"),
            exchange=enums.CryptoHoldingExchangeEnum.coinbase,
        ),
    ]

    for holding in holdings:
        holding.add_crypto_holding(config.session)
        print(f"Added crypto: {holding.name}")


def seed_transactions():
    if check_transactions_exist():
        print("Transactions already exist, skipping...")
        return

    today = datetime.now()
    start_date = today - timedelta(days=180)

    transactions = []

    current_date = start_date
    while current_date <= today:
        if current_date.weekday() == 4:
            transactions.append(
                Transactions(
                    amount=Decimal(str(random.uniform(2500, 3200))),
                    category=enums.TransactionCategoryEnum.savings,
                    description=f"Bi-weekly paycheck - {current_date.strftime('%Y-%m-%d')}",
                    date=current_date,
                    type=enums.TransactionTypeEnum.income,
                    savings_goal_id=None,
                )
            )

        transactions.append(
            Transactions(
                amount=Decimal("1400.00"),
                category=enums.TransactionCategoryEnum.rent,
                description="Monthly rent payment",
                date=current_date.replace(day=1),
                type=enums.TransactionTypeEnum.expense,
                savings_goal_id=None,
            )
        )

        for _ in range(random.randint(2, 4)):
            transactions.append(
                Transactions(
                    amount=Decimal(str(random.uniform(30, 80))),
                    category=enums.TransactionCategoryEnum.food,
                    description=fake.sentence(nb_words=4),
                    date=current_date - timedelta(days=random.randint(0, 5)),
                    type=enums.TransactionTypeEnum.expense,
                    savings_goal_id=None,
                )
            )

        if random.random() < 0.3:
            transactions.append(
                Transactions(
                    amount=Decimal(str(random.uniform(20, 60))),
                    category=enums.TransactionCategoryEnum.transport,
                    description=fake.sentence(nb_words=3),
                    date=current_date,
                    type=enums.TransactionTypeEnum.expense,
                    savings_goal_id=None,
                )
            )

        if random.random() < 0.2:
            transactions.append(
                Transactions(
                    amount=Decimal(str(random.uniform(15, 80))),
                    category=enums.TransactionCategoryEnum.entertainment,
                    description=fake.sentence(nb_words=3),
                    date=current_date,
                    type=enums.TransactionTypeEnum.expense,
                    savings_goal_id=None,
                )
            )

        if current_date.day == 15:
            transactions.extend([
                Transactions(
                    amount=Decimal(str(random.uniform(40, 80))),
                    category=enums.TransactionCategoryEnum.utilities,
                    description="Electric bill",
                    date=current_date,
                    type=enums.TransactionTypeEnum.expense,
                    savings_goal_id=None,
                ),
                Transactions(
                    amount=Decimal(str(random.uniform(60, 100))),
                    category=enums.TransactionCategoryEnum.utilities,
                    description="Internet bill",
                    date=current_date,
                    type=enums.TransactionTypeEnum.expense,
                    savings_goal_id=None,
                ),
            ])

        if random.random() < 0.4:
            transactions.append(
                Transactions(
                    amount=Decimal(str(random.uniform(10, 20))),
                    category=enums.TransactionCategoryEnum.subscriptions,
                    description=random.choice(["Netflix", "Spotify", "Disney+", "Hulu", "Amazon Prime"]),
                    date=current_date,
                    type=enums.TransactionTypeEnum.expense,
                    savings_goal_id=None,
                )
            )

        if random.random() < 0.1:
            transactions.append(
                Transactions(
                    amount=Decimal(str(random.uniform(100, 300))),
                    category=enums.TransactionCategoryEnum.concerts,
                    description=f"Concert: {fake.name()}",
                    date=current_date,
                    type=enums.TransactionTypeEnum.expense,
                    savings_goal_id=None,
                )
            )

        transactions.append(
            Transactions(
                amount=Decimal(str(random.uniform(100, 500))),
                category=enums.TransactionCategoryEnum.savings,
                description="Transfer to savings",
                date=current_date,
                type=enums.TransactionTypeEnum.expense,
                savings_goal_id=1,
            )
        )

        current_date += timedelta(days=14)

    for txn in transactions:
        txn.add_transaction(config.session)

    print(f"Added {len(transactions)} transactions")


def main():
    print("Starting database seed...")
    print("-" * 40)

    seed_savings_goals()
    seed_debts()
    seed_crypto_holdings()
    seed_transactions()

    print("-" * 40)
    print("Database seeding complete!")


if __name__ == "__main__":
    main()
